### ISSUE TITLE
Lead not working on Villagers

### ISSUE THREAD

**Issue by mahilo3550** [strikerrocker/ModJam-5#1]
MC 1.12.2 Forge 14.23.2.2654 Mod 1.1

Right-clicking with a lead on a Villager does nothing.

**Comment by KaptainWutax** [comment]
We at this instant working on the bug. Thanks for the report! :D

**Comment by strikerrocker** [comment]
Looking at this. It may not be possible to make it compat with existing villagers so the only way is to make it so that only newly spawned villager are leashable but yet i am not 100% sure

**Comment by strikerrocker** [comment]
So you working on this i assume?
