### ISSUE TITLE
Place below not working

### ISSUE THREAD

**Issue by VallenFrostweaver** [strikerrocker/ModJam-5#2]
I can't seem to get the place below working with the keybind, with shift and the keybind, or even if I change the keys and try again.

**Comment by KaptainWutax** [comment]
The issue was patched over a week ago but we didn't push the jar yet. I will do as soon as I can! :D

**Comment by KaptainWutax** [comment]
It will not be acceptable for ModJam but we will still continue the development of the mod. We already sent the jar for the event. :D

**Comment by VallenFrostweaver** [comment]
I couldn't get the Hopper > jukebox > hopper to work either. Is that expected too?

**Comment by KaptainWutax** [comment]
That is very strange. It should work. I think there was an error with building the jar, thanks for letting me know!

**Comment by KaptainWutax** [comment]
I uploaded a bug fix and a bunch of new features! *Giggly Scream* Let me know if it works so I can close this issue! :D
